### ISSUE TITLE
Training DECIMER on a new dataset with GPU. 

### ISSUE THREAD

**Issue by lucasmorin222** [Kohulan/DECIMER-Image_Transformer#41]
Hello, 
Is it possible to train DECIMER on a new dataset consisting of pairs of images and SMILES, and without having access to TPUs?
Best,
Lucas

**Comment by Kohulan** [comment]
Hi @lucasmorin222 ,

In principle, you can. But the current training scripts are written to be trained on TPUs,
You could use the [MirroredStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy) instead of the TPU strategy to train on GPU.

Please remove these lines from the training script 
```python
tpu = tf.distribute.cluster_resolver.TPUClusterResolver(tpu="node-name")
print("Running on TPU ", tpu.master())

tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)
strategy = tf.distribute.TPUStrategy(tpu)
```

and replace it with the following:
```python
strategy = tf.distribute.MirroredStrategy(["GPU:0", "GPU:1"])
```

You can still use TFRecords to train on GPUs so no need to change anything there.

Regards,
Kohulan
