### ISSUE TITLE
The model cannot recognize pretty simple structures.

### ISSUE THREAD

**Issue by BinaryBlaze291** [Kohulan/DECIMER-Image_Transformer#51]
### Issue Type

Performance

### Source

GitHub (source)

### DECIMER Image Transformer Version

2.2.0

### Current Behaviour?

The model cannot recognize pretty simple structures. I tried all of these and it gives wrong results
![ethanol](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/76c9932f-5caa-452d-85a5-111965e83cf7)
![structural-formula-propane-chemical-formula-skeletal-formula-chemical-compound-png-favpng-at97Lc9JR8GCLVnKdUFphiUpg](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/3ea47112-5b1f-4389-850a-6fdc6dbef694)
![ethane-flat3134352308631709013](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/cbdb9505-8ee0-464e-9882-e418902bf77b)
![q_3_21_july201166500841672020](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/68a703b4-b50b-4e22-9e31-78d4e243e859)

### Standalone code to reproduce the issue

```shell
Just use the provided images as input
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by BinaryBlaze291** [comment]
I even tried it on hand drawn structures and none of the predictions were correct
![struct4_02](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/ffc2526d-c4f2-4d3a-ac83-0fdbfad70e14)
![struct5_06](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/4426c2d0-61b4-40e0-8b00-b3d7c3e7d145)
![struct8_04](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/5e53958f-a1a1-4c43-beca-2c8535f62f9c)
![struct16_02](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/7a28eae0-d31d-4198-9b4c-9acee737004e)
![struct19_03](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/79436994-03e1-4bf1-9e8d-cac010878ef6)
![struct20_08](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/5806aee9-288d-46e8-9396-819a6c6db126)
![struct20_09](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/29e02571-fb48-4e41-afff-44c2d1755076)
![struct22_04](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/dbb7b0fa-75c2-4b91-b441-d8c52cfb0d67)
![struct22_05](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/69635240/34ca5063-1d97-4b63-b450-20d8fa525715)

**Comment by OBrink** [comment]
Hello @BinaryBlaze291,

Thank you for the report! 

About the first three depictions - We currently do not include explicit hydrogen atoms in the training data (unless they are essential for the stereochemistry), as the depictions of large molecules tend to get very messy with overlapping elements. This leads to the tool's inability to interpret them. I agree that it should not have problems with this kind of simple structure. I will push a fix to RanDepict so that a proportion of the molecules with < 15 heavy atoms is depicted with explicit hydrogen atoms in the future. This should fix the issue in the future.

About the hand-drawn structures - this is more complicated and hard to say. The ability to read chemical structures at all is rather a side effect that came with the diversification of the training data. We'll have a look at it. The background could potentially be a problem here. You could try binarising the images before processing them with DECIMER Image Transformer.

Kind regards,
Otto

**Comment by OBrink** [comment]
Here's an example of a binarised hand-drawn depiction vs the original image:
<img width="640" alt="PastedGraphic-1" src="https://github.com/Kohulan/DECIMER-Image_Transformer/assets/59618901/99ec54fe-18f2-4626-a94f-7d0980cfe54b">
![PastedGraphic-2](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/59618901/b6641fe9-91b5-4c79-b907-18ba9cdb77e6)

**Comment by steinbeck** [comment]
Here is another one.
![example2](https://github.com/Kohulan/DECIMER-Image_Transformer/assets/107318/20d24be8-d4e4-4ba7-9d9b-8198395f478d)

**Comment by OBrink** [comment]
@BinaryBlaze291 

We have added explicit hydrogen atoms to the depictions in our training data. The next version of DECIMER Image Transformer will be capable of handling structures that contain them. Thank you for bringing this to our attention!

**Comment by OBrink** [comment]
The new version of the model that @Kohulan has released today is capable of handling the hand-drawn structures posted @BinaryBlaze291

**Comment by OBrink** [comment]
@BinaryBlaze291, we start creating a new dataset now that contains depictions with explicit hydrogen atoms. Additionally, the model will be trained to return cxSMILES with atom coordinates. 

I will close this issue for now, as it will probably take a little while until the new model is ready to be published. Again, thank you for bringing these issues to our attention! The lack of recognition capabilities for explicit hydrogen atoms is a big blind spot of the current model version that will be fixed soon.
